@startuml

title Procédure d'inscription Sherbrooke \n

group Démarche envers l'ESEO
Etudiant -> ESEO: Assister aux réunions inutiles Bi-diplome
Etudiant -> ESEO: Remplir et envoier le formulaire de pré-inscription au près du service international
ESEO -> Etudiant: S'informer de la validité du Bi-diplôme choisi au près du directeur d'étude
end

group Début des démarches
Etudiant -> Sherbrooke: Demande d'inscription (online)
Sherbrooke -> Sherbrooke: Un à deux mois d'attente
Sherbrooke -> Etudiant: Inscirption validée
note left
Validation de l'Université
obligatoire avant toute autres démarches
end note
end

group Papiers canadien
Etudiant -> Ministere_Canadien: Demande CAQ
Ministere_Canadien -> Ministere_Canadien: Un à deux mois d'attente
Ministere_Canadien -> Etudiant: CAQ Validé
note left
Validation du CAQ
obligatoire avant toute autres démarches
end note
Etudiant -> Ministere_Canadien: Demande de permis d'étude
Ministere_Canadien -> Ministere_Canadien: 3 semaines
Ministere_Canadien -> Etudiant: Permis étude validé
end

group Assurances
Etudiant -> CPAM: Demande de dérogation aux assurances RAMQ (envoie du formulaire SE-401- Q102 à la CPAM)
CPAM -> CPAM: 3 semaines (peu être réduit à une semaine avec de la chance)
CPAM -> Etudiant: Formulaire retournée tamponné
Etudiant -> Assurances: Assurances pour le Québec ("Passport" pour SMEBA ou autre)
Assurances -> Etudiant: Carte d'assuré
end

group Bourse
ESEO -> Etudiant: Envoie code pour bourse Envoléo
Etudiant -> Envoléo: Demande bourse Envoleo (débout juin)
Etudiant -> ESEO: Envoie des documents Envoleo
end

group Faciliter l'arrivée
Etudiant -> VAE: Demande VAE (online)
Etudiant -> Accueil_Plus: Demande Accueil_Plus (online)
VAE -> Etudiant: Réponse VAE (online)
Accueil_Plus -> Etudiant: Réponse Accueil_Plus (online)
end

Etudiant -> Etudiant: Bye bye calisse d'ESEO!

@enduml
